id: IDB841B14
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-04-01T11:59:57+00:00'
last_modified: '2022-06-16T05:11:18.813028+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16666
  title: རྔོག་སློབ་བརྒྱུད་དང་བཅས་པའི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '3915':
      image_group_id: I4PD2667
      title: ''
      total_pages: ''
      order: 1
      base_file: 3915.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
